version: '3.8'

services:
  db:
    container_name: db
    image: postgres:16.2
    environment:
      - POSTGRES_DB=${DB_NAME_TEST}
      - POSTGRES_USER=${DB_USER_TEST}
      - POSTGRES_PASSWORD=${DB_PASS_TEST}
    ports:
      - ${DB_PORT_TEST}:5432
    restart: always
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER}']
      interval: 10s
      timeout: 5s
      retries: 5
  tests:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: tests
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '8000:8000'
    env_file:
      - .env
    volumes:
      - ./:/backend/
    networks:
      - backend

networks:
  backend:
    driver: "bridge"
